import type { MetricEngine } from '~/entities/metric'

export const additionalAlphaMetric: MetricEngine = {
  key: 'additional_alpha',
  category: 'adherence',
  i18n: {
    ru: {
      label: 'Дополнительная альфа',
      sub: 'Прибыль от доп. слоев',
      desc: 'Альфа PnL, полученная от дополнительных подтверждающих условий по сравнению с базой.',
      formula: '((PnL - Средний PnL) / Средний PnL) * 100',
      benchmark: '> 0% (Положительная альфа)',
      evaluation: 'Прирост профита от дополнительных фильтров.'
    },
    en: {
      label: 'Additional Alpha',
      sub: 'Extra confirmation yield',
      desc: 'Calculates the PnL alpha generated by adding extra confirmation layers compared to strategy baseline.',
      formula: '((PnL - Average PnL) / Average PnL) * 100',
      benchmark: '> 0% (Positive Alpha)',
      evaluation: 'Excess yield from additional confirmation layers.'
    }
  },
  calculate(trade: any, context?: any, locale: 'ru' | 'en' = 'ru') {
    const isRu = locale === 'ru'
    const pnl = Number(trade?.pnl || trade?.profit || 0)
    const avgPnl = Number(context?.avgPnl ?? 0)
    const alpha = avgPnl > 0 ? ((pnl - avgPnl) / avgPnl) * 100 : 0

    const isPositive = alpha >= 0
    const evalClass = isPositive ? 'text-emerald-500' : 'text-rose-500'

    return {
      rawValue: alpha,
      formattedValue: `${isPositive ? '+' : ''}${alpha.toFixed(2)}%`,
      status: isPositive ? 'optimal' : 'critical',
      evaluationText: isPositive ? (isRu ? 'Положительно' : 'Positive') : (isRu ? 'Отрицательно' : 'Negative'),
      evalClass,
      benchmarkText: isRu ? '> 0% — Прирост альфы' : '> 0% — Positive Alpha',
      benchmarks: [
        { label: '> 0%', eval: isRu ? 'Положительная альфа' : 'Positive Alpha', class: 'text-emerald-500 font-bold' },
        { label: '< 0%', eval: isRu ? 'Отрицательная просадка' : 'Negative Drag', class: 'text-rose-500 font-bold' }
      ],
      progress: Math.min(100, Math.max(0, 50 + alpha)),
      colorVal: isPositive ? '#34d399' : '#f87171'
    }
  }
}
