import type { MetricEngine } from '~/entities/metric'

export const netProfitMetric: MetricEngine = {
  key: 'netProfit',
  category: 'simple',
  i18n: {
    ru: {
      label: 'Чистая прибыль',
      sub: 'Итоговый PnL сделки',
      desc: 'Фактически зафиксированный чистый финансовый результат после полного закрытия сделки.',
      formula: 'Валовая прибыль - Валовой убыток',
      benchmark: '> $0.00 (Прибыльный исход)',
      evaluation: 'Финансовый доход позиции.'
    },
    en: {
      label: 'Net Profit',
      sub: 'Realized trade PnL',
      desc: 'Net realized financial result after full trade liquidation.',
      formula: 'Gross Profit - Gross Loss',
      benchmark: '> $0.00 (Profitable Outcome)',
      evaluation: 'Net dollar return generated by position.'
    }
  },
  calculate(trade: any, _context?: any, locale: 'ru' | 'en' = 'ru') {
    const pnl = Number(trade?.pnl || trade?.profit || 0)

    const isRu = locale === 'ru'
    let status: 'optimal' | 'stable' | 'neutral' | 'warning' | 'critical' = 'neutral'
    let evalText = isRu ? 'Безубыток' : 'Break-even'
    let evalClass = 'text-amber-400'
    let colorVal = '#fbbf24'

    if (pnl > 0) {
      status = 'optimal'
      evalText = isRu ? 'Прибыль' : 'Profitable'
      evalClass = 'text-emerald-400 font-bold'
      colorVal = '#34d399'
    } else if (pnl < 0) {
      status = 'critical'
      evalText = isRu ? 'Убыток' : 'Drawdown'
      evalClass = 'text-rose-500 font-bold'
      colorVal = '#f43f5e'
    }

    const formattedValue = `${pnl > 0 ? '+' : pnl < 0 ? '-' : ''}$${Math.abs(pnl).toLocaleString(undefined, { minimumFractionDigits: 2, maximumFractionDigits: 2 })}`

    return {
      rawValue: pnl,
      formattedValue,
      status,
      evaluationText: evalText,
      evalClass,
      benchmarkText: isRu ? '> $0.00 — Положительный доход' : '> $0.00 — Positive Return',
      benchmarks: [
        { label: '> $0.00', eval: isRu ? 'Прибыль' : 'Profitable', class: 'text-emerald-400 font-bold' },
        { label: '$0.00', eval: isRu ? 'Безубыток' : 'Break-even', class: 'text-amber-400' },
        { label: '< $0.00', eval: isRu ? 'Убыток' : 'Drawdown', class: 'text-rose-500 font-bold' }
      ],
      progress: Math.min(100, Math.max(0, 50 + (pnl / 20))),
      colorVal
    }
  }
}
