export const matrixTextKeys: Record<string, string> = {
  LOGIC: 'matrix.categoryLogic',
  METHODS: 'matrix.categoryMethods',
  DATA: 'matrix.categoryData',
  DOMAINS: 'matrix.categoryDomains',
  INDICATORS: 'matrix.categoryIndicators',
  EMOTIONS: 'matrix.categoryEmotions',
  STEPS: 'matrix.categorySteps',
  SCALING: 'matrix.categoryScaling',
  RISK: 'matrix.categoryRisk',
  LABELS: 'matrix.categoryLabels',
  SYSTEM: 'matrix.categorySystem',
  DOCS: 'matrix.categoryDocs',
  VISUALS: 'matrix.categoryVisuals',
  AUDIO: 'matrix.categoryAudio',
  TEXT: 'matrix.categoryText',
  'TEXT PANEL': 'matrix.textPanel',
  LABEL: 'matrix.label',
  'TEXT INPUT PANEL': 'matrix.textInputPanel',
  'CHECKLIST PANEL': 'matrix.checklistPanel',
  CHECK: 'matrix.check',
  'TABLE PANEL': 'matrix.tablePanel',
  TABLE: 'matrix.table',
  'STRUCTURED TABLE PANEL': 'matrix.structuredTablePanel',
  'EMBED PANEL': 'matrix.embedPanel',
  EMBED: 'matrix.embed',
  SCREENSHOT: 'matrix.screenshot',
  SHOT: 'matrix.shot',
  'SCREENSHOT EVIDENCE': 'matrix.screenshotEvidence',
  'DRAWING PANEL': 'matrix.drawingPanel',
  DRAW: 'matrix.draw',
  'FULLSCREEN DRAWING BOARD': 'matrix.fullscreenDrawingBoard',
  'FILE ATTACHMENT': 'matrix.fileAttachment',
  FILE: 'matrix.file',
  'Pyramiding': 'matrix.pyramiding',
  'Averaging': 'matrix.averaging',
  'Strategy': 'matrix.strategy',
  'Scenario': 'matrix.scenario',
  'Condition': 'matrix.condition',
  'Emotion': 'matrix.emotion',
  'Risk': 'matrix.risk',
  'Visual': 'matrix.visual',
  'START': 'matrix.start',
  'PAUSE': 'matrix.pause',
  'RESUME': 'matrix.resume',
  'FINISH': 'matrix.finish',
  'FIRST CHECK': 'matrix.firstCheck',
  'SECOND CHECK': 'matrix.secondCheck',
  'INITIALIZE SIGNAL INDICATOR': 'matrix.initializeSignalIndicator',
  'Incremental position scaling in the direction of trend momentum.': 'matrix.pyramidingDescription',
  'Strategic entry distribution to optimize the aggregate cost basis.': 'matrix.averagingDescription',
  'Free-form text label for long labels or sentences.': 'matrix.textPanelDescription',
  'Interactive checklist panel for scenario tasks and validation points.': 'matrix.checklistDescription',
  'Structured table panel with fixed full-cell inputs and auto sizing.': 'matrix.tableDescription',
  'Embed panel for external URLs, references, and media links.': 'matrix.embedDescription',
  'Screenshot evidence node for chart states, execution examples, and annotations.': 'matrix.screenshotDescription',
  'Fullscreen drawing panel for mapping scenario structure, paths, and notes.': 'matrix.drawingDescription',
  'Attach a file to the scenario archive.': 'matrix.fileDescription',
  'Risk management protocol defining loss constraints and exposure limits.': 'matrix.riskDescription',
  'ENTRY ZONE': 'matrix.zoneEntry',
  'IN-TRADE ZONE': 'matrix.zoneInTrade',
  'EXIT ZONE': 'matrix.zoneExit',
  'SESSION ZONE': 'matrix.zoneSession',
  entry: 'matrix.zoneEntryShort',
  'in-trade': 'matrix.zoneInTradeShort',
  exit: 'matrix.zoneExitShort',
  session: 'matrix.zoneSessionShort'
}

export const matrixNodeTypeKeys: Record<string, string> = {
  strategy: 'matrix.strategy',
  scenario: 'matrix.scenario',
  condition: 'matrix.condition',
  conditions: 'matrix.conditions',
  indicator: 'matrix.indicator',
  pattern: 'matrix.pattern',
  smc: 'matrix.smc',
  data: 'matrix.dataNode',
  methods: 'matrix.methodsNode',
  risk: 'matrix.risk',
  'risk-management': 'matrix.riskManagement',
  'risk-element': 'matrix.riskElement',
  emotion: 'matrix.emotion',
  'emotion-state': 'matrix.emotionState',
  instrument: 'matrix.instrument',
  pyramiding: 'matrix.pyramiding',
  averaging: 'matrix.averaging',
  domain: 'matrix.domain',
  'scaling-entry': 'matrix.scalingEntry',
  'text-panel': 'matrix.textPanel',
  'checklist-panel': 'matrix.checklistPanel',
  'table-panel': 'matrix.tablePanel',
  'embed-panel': 'matrix.embedPanel',
  image: 'matrix.image',
  'drawing-panel': 'matrix.drawingPanel',
  'file-attachment': 'matrix.fileAttachment',
  'audio-note': 'matrix.audioNote',
  step: 'matrix.step',
  placeholder: 'matrix.placeholder',
  node: 'matrix.node'
}

export function matrixText(t: (key: string) => string, value: string) {
  return t(matrixTextKeys[value] || value)
}

export function matrixNodeTypeLabel(t: (key: string) => string, value: string) {
  return t(matrixNodeTypeKeys[value] || value)
}
